version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"
    groups:
      django-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "dj*"
        update-types:
          - "minor"
          - "patch"
      python-patch:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "dj*"
        update-types:
          - "patch"
      python-minor:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "dj*"
        update-types:
          - "minor"
      python-major:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"
