# Generated by Django 5.1.3 on 2025-02-14 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("taxonomy_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("rank", models.CharField(max_length=255)),
            ],
            options={
                "indexes": [models.Index(fields=["taxonomy_id"], name="taxonomy_ta_taxonom_9ea754_idx")],
            },
        ),
        migrations.CreateModel(
            name="Range",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("database", models.CharField(max_length=32)),
                ("start", models.IntegerField(blank=True, null=True)),
                ("end", models.IntegerField(blank=True, null=True)),
                (
                    "taxonomy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="taxonomy.taxonomy",
                        to_field="taxonomy_id",
                    ),
                ),
            ],
        ),
    ]
