# Generated by Django 5.1.3 on 2024-12-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("taxonomy_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("rank", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
