# Generated by Django 5.2 on 2025-07-18 08:26

import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("rank", models.CharField(max_length=255)),
                (
                    "search",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.contrib.postgres.search.SearchVector("name", config="simple"),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_set",
                        to="taxonomy.taxonomy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Range",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("database", models.CharField(max_length=32)),
                ("start", models.IntegerField(blank=True, null=True)),
                ("end", models.IntegerField(blank=True, null=True)),
                (
                    "taxonomy",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="taxonomy.taxonomy"
                    ),
                ),
            ],
        ),
    ]
