# Generated by Django 5.2 on 2026-02-05 11:07

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="range",
            name="id",
        ),
        migrations.AddField(
            model_name="range",
            name="pk",
            field=models.CompositePrimaryKey(
                "taxonomy", "database", blank=True, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="range",
            name="taxonomy",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="taxonomy.taxonomy"),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="range",
            index=models.Index(fields=["taxonomy", "database"], name="taxonomy_ra_taxonom_b7d953_idx"),
        ),
        migrations.AddIndex(
            model_name="taxonomy",
            index=django.contrib.postgres.indexes.GinIndex(fields=["search"], name="taxonomy_ta_search_dee482_gin"),
        ),
    ]
