# Generated by Django 5.1.3 on 2024-12-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="taxonomy",
            index=models.Index(fields=["taxonomy_id"], name="taxonomy_ta_taxonom_9ea754_idx"),
        ),
    ]
