# Generated by Django 5.1.3 on 2025-02-19 13:01

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxonomy",
            name="search",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.SearchVector("name", config="simple"),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
    ]
