# Generated by Django 5.2 on 2026-02-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0002_remove_range_id_range_pk_alter_range_taxonomy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxonomy",
            name="depth",
            field=models.PositiveIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taxonomy",
            name="lft",
            field=models.PositiveIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taxonomy",
            name="rgt",
            field=models.PositiveIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taxonomy",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
