# Generated by Django 5.1.3 on 2025-04-09 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0002_taxonomy_search"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="taxonomy",
            name="taxonomy_ta_taxonom_9ea754_idx",
        ),
        migrations.RemoveField(
            model_name="taxonomy",
            name="depth",
        ),
        migrations.RemoveField(
            model_name="taxonomy",
            name="numchild",
        ),
        migrations.RemoveField(
            model_name="taxonomy",
            name="path",
        ),
        migrations.AddField(
            model_name="taxonomy",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children_set",
                to="taxonomy.taxonomy",
            ),
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="taxonomy_id",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
