# Generated by Django 5.1.3 on 2024-12-19 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0002_taxonomy_taxonomy_ta_taxonom_9ea754_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxonomy",
            name="taxonomy_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name="Range",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("database", models.CharField(max_length=32)),
                ("start", models.IntegerField(blank=True, null=True)),
                ("end", models.IntegerField(blank=True, null=True)),
                (
                    "taxonomy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="taxonomy.taxonomy",
                        to_field="taxonomy_id",
                    ),
                ),
            ],
        ),
    ]
