# Generated by Django 5.1.3 on 2025-01-23 14:21

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_results", "0011_taskresult_periodic_task_name"),
        ("search", "0002_alter_hmmerjob_result_json_alter_hmmerjob_result_pkl"),
        ("taxonomy", "0003_alter_taxonomy_taxonomy_id_range"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxonomyJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tree",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url="/results/", location="/app/media/results"
                        ),
                        upload_to="%Y/%m/%d",
                    ),
                ),
                (
                    "hmmer_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="taxonomy_job", to="search.hmmerjob"
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxonomy_job",
                        to="django_celery_results.taskresult",
                        to_field="task_id",
                    ),
                ),
            ],
        ),
    ]
