# Generated by Django 5.1.3 on 2025-04-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0003_remove_taxonomy_taxonomy_ta_taxonom_9ea754_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxonomy",
            name="taxonomy_id",
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
