# Generated by Django 5.1.3 on 2025-04-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0004_remove_taxonomy_taxonomy_id_alter_range_taxonomy_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Range",
        ),
    ]
