# Generated by Django 5.1.3 on 2025-04-09 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0005_delete_range"),
    ]

    operations = [
        migrations.CreateModel(
            name="Range",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("database", models.CharField(max_length=32)),
                ("start", models.IntegerField(blank=True, null=True)),
                ("end", models.IntegerField(blank=True, null=True)),
                (
                    "taxonomy",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="taxonomy.taxonomy"
                    ),
                ),
            ],
        ),
    ]
