# Generated by Django 5.1.3 on 2025-03-13 12:01

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_celery_results", "0011_taskresult_periodic_task_name"),
        ("search", "0009_hmmerjob_annotation_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("format", models.CharField(max_length=32)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url="/downloads/",
                            location="/Users/aleksandar/Documents/djhmmer_temp/hmmer-api/downloads",
                        ),
                        upload_to="",
                    ),
                ),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="search.hmmerjob")),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="django_celery_results.taskresult",
                    ),
                ),
            ],
        ),
    ]
