# Generated by Django 5.1.3 on 2025-03-13 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("download", "0001_initial"),
        ("search", "0009_hmmerjob_annotation_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filejob",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="search.hmmerjob"
            ),
        ),
    ]
