# Generated by Django 5.1.3 on 2025-03-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("download", "0002_alter_filejob_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="filejob",
            name="filters",
            field=models.JSONField(default=dict),
        ),
    ]
