# Generated by Django 5.1.3 on 2025-02-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("architecture", "0001_initial"),
        ("architecture", "0002_remove_architecture_database_and_more"),
        ("architecture", "0003_architecture_architectur_accessi_ac05b2_idx"),
        ("architecture", "0004_architecture_database_architecture_sequence_index"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Architecture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.PositiveIntegerField()),
                ("accessions", models.TextField()),
                ("names", models.TextField()),
                ("graphics", models.TextField()),
                ("database", models.CharField(default=None, max_length=32)),
                ("sequence_index", models.BigIntegerField()),
            ],
            options={
                "indexes": [models.Index(fields=["accessions"], name="architectur_accessi_ac05b2_idx")],
            },
        ),
    ]
