# Generated by Django 5.1.3 on 2025-03-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("architecture", "0001_squashed_0004_architecture_database_architecture_sequence_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="architecture",
            name="database",
            field=models.CharField(max_length=32),
        ),
    ]
