# Generated by Django 5.2 on 2025-04-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("architecture", "0005_alter_architecture_database"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="architecture",
            name="id",
        ),
        migrations.AddField(
            model_name="architecture",
            name="pk",
            field=models.CompositePrimaryKey(
                "sequence_index", "database", blank=True, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
