# Generated by Django 5.2 on 2025-04-27 09:36

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("architecture", "0006_remove_architecture_id_architecture_pk"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="architecture",
            name="architectur_accessi_ac05b2_idx",
        ),
        migrations.AddIndex(
            model_name="architecture",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["accessions"], name="architectur_accessi_f7e6b8_hash"
            ),
        ),
    ]
