# Generated by Django 5.2 on 2025-04-30 08:14

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("architecture", "0007_remove_architecture_architectur_accessi_ac05b2_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="architecture",
            name="architectur_accessi_f7e6b8_hash",
        ),
        migrations.AddIndex(
            model_name="architecture",
            index=models.Index(fields=["sequence_index", "database"], name="architectur_sequenc_85ae62_idx"),
        ),
        migrations.AddIndex(
            model_name="architecture",
            index=models.Index(django.db.models.functions.text.MD5("accessions"), name="idx_accessions_md5"),
        ),
    ]
