# Generated by Django 5.2 on 2025-05-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("architecture", "0008_remove_architecture_architectur_accessi_f7e6b8_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="architecture",
            name="graphics",
            field=models.JSONField(),
        ),
    ]
