# Generated by Django 5.1.3 on 2024-12-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhmmerJob",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("search.hmmerjob",),
        ),
    ]
