# Generated by Django 5.1.3 on 2025-02-13 10:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_celery_results", "0011_taskresult_periodic_task_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="HmmerJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                (
                    "algo",
                    models.CharField(
                        choices=[
                            ("phmmer", "Phmmer"),
                            ("hmmsearch", "Hmmsearch"),
                            ("hmmscan", "Hmmscan"),
                            ("jackhmmer", "Jackhmmer"),
                        ],
                        default="phmmer",
                        max_length=16,
                    ),
                ),
                ("database", models.CharField(max_length=32)),
                ("sequence", models.TextField()),
                ("E", models.FloatField(blank=True, default=1.0, null=True)),
                ("domE", models.FloatField(blank=True, default=1.0, null=True)),
                ("T", models.FloatField(blank=True, default=7.0, null=True)),
                ("domT", models.FloatField(blank=True, default=5.0, null=True)),
                ("incE", models.FloatField(blank=True, default=0.01, null=True)),
                ("incdomE", models.FloatField(blank=True, default=0.03, null=True)),
                ("incT", models.FloatField(blank=True, default=25.0, null=True)),
                ("incdomT", models.FloatField(blank=True, default=22.0, null=True)),
                ("popen", models.FloatField(blank=True, default=0.02, null=True)),
                ("pextend", models.FloatField(blank=True, default=0.4, null=True)),
                (
                    "mx",
                    models.CharField(
                        choices=[
                            ("BLOSUM62", "Blosum62"),
                            ("BLOSUM45", "Blosum45"),
                            ("BLOSUM90", "Blosum90"),
                            ("PAM30", "Pam30"),
                            ("PAM70", "Pam70"),
                            ("PAM250", "Pam250"),
                        ],
                        default="BLOSUM62",
                        max_length=16,
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_results.taskresult",
                    ),
                ),
            ],
        ),
    ]
