# Generated by Django 5.1.3 on 2024-12-10 14:05

import django.core.files.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_celery_results", "0011_taskresult_periodic_task_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="HmmerJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                (
                    "algo",
                    models.CharField(
                        choices=[
                            ("PHMMER", "Phmmer"),
                            ("HMMSEARCH", "Hmmsearch"),
                            ("HMMSCAN", "Hmmscan"),
                            ("JACKHMMER", "Jackhmmer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("params", models.JSONField(default=dict)),
                (
                    "result_pkl",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url="/results/", location="/Users/aleksandar/Documents/DjHmmer/hmmer_api/media/results"
                        ),
                        upload_to="%Y/%m/%d",
                    ),
                ),
                (
                    "result_json",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url="/results/", location="/Users/aleksandar/Documents/DjHmmer/hmmer_api/media/results"
                        ),
                        upload_to="%Y/%m/%d",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hmmer_job",
                        to="django_celery_results.taskresult",
                        to_field="task_id",
                    ),
                ),
            ],
        ),
    ]
