# Generated by Django 5.1.3 on 2025-02-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmmerjob",
            name="threshold",
            field=models.CharField(
                choices=[("evalue", "Evalue"), ("bitscore", "Bitscore"), ("cut_ga", "Cut Ga")],
                default="evalue",
                max_length=16,
            ),
        ),
    ]
