# Generated by Django 5.1.3 on 2025-02-14 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_results", "0011_taskresult_periodic_task_name"),
        ("search", "0002_hmmerjob_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmmerjob",
            name="taxonomy_distribution_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="django_celery_results.taskresult",
            ),
        ),
        migrations.AddField(
            model_name="hmmerjob",
            name="taxonomy_tree_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="django_celery_results.taskresult",
            ),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="django_celery_results.taskresult",
            ),
        ),
    ]
