# Generated by Django 5.1.3 on 2025-02-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_hmmerjob_taxonomy_distribution_task_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmmerjob",
            name="with_architecture",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hmmerjob",
            name="with_taxonomy",
            field=models.BooleanField(default=False),
        ),
    ]
