# Generated by Django 5.1.3 on 2025-03-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0006_hmmerjob_taxonomy_distribution_graph_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hmmerjob",
            old_name="sequence",
            new_name="input",
        ),
    ]
