# Generated by Django 5.1.3 on 2025-03-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0007_rename_sequence_hmmerjob_input"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hmmerjob",
            name="mx",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BLOSUM62", "Blosum62"),
                    ("BLOSUM45", "Blosum45"),
                    ("BLOSUM90", "Blosum90"),
                    ("PAM30", "Pam30"),
                    ("PAM70", "Pam70"),
                    ("PAM250", "Pam250"),
                ],
                default="BLOSUM62",
                max_length=16,
                null=True,
            ),
        ),
    ]
