# Generated by Django 5.1.3 on 2025-03-11 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_results", "0011_taskresult_periodic_task_name"),
        ("search", "0008_alter_hmmerjob_mx"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmmerjob",
            name="annotation_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="django_celery_results.taskresult",
            ),
        ),
    ]
