# Generated by Django 5.1.3 on 2025-04-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0009_hmmerjob_annotation_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                ("id", models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ("type", models.CharField(choices=[("seq", "Seq"), ("hmm", "Hmm")], default="seq", max_length=16)),
                ("name", models.CharField(max_length=32)),
                ("version", models.CharField(max_length=32)),
                ("release_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
