# Generated by Django 5.1.3 on 2025-04-09 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0011_alter_database_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="database",
            name="release_date",
            field=models.DateField(default=datetime.date(2025, 4, 9)),
        ),
    ]
