# Generated by Django 5.1.3 on 2025-04-11 12:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0012_alter_database_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="database",
            name="release_date",
            field=models.DateField(default=datetime.date(2025, 4, 11)),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="database",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="search.database",
            ),
        ),
    ]
