# Generated by Django 5.2 on 2025-04-17 08:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0013_alter_database_release_date_alter_hmmerjob_database"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmmerjob",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children_set",
                to="search.hmmerjob",
            ),
        ),
        migrations.AlterField(
            model_name="database",
            name="release_date",
            field=models.DateField(default=datetime.date(2025, 4, 17)),
        ),
    ]
