# Generated by Django 5.2 on 2025-04-22 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0014_hmmerjob_parent_alter_database_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="database",
            name="release_date",
            field=models.DateField(default=datetime.date(2025, 4, 22)),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="input",
            field=models.TextField(blank=True, null=True),
        ),
    ]
