# Generated by Django 5.2 on 2025-04-30 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0014_alter_database_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="database",
            name="release_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
