# Generated by Django 5.2 on 2025-05-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0015_alter_database_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="database",
            name="order",
            field=models.IntegerField(default=-1),
        ),
    ]
