# Generated by Django 5.2 on 2025-04-22 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0015_alter_database_release_date_alter_hmmerjob_input"),
    ]

    operations = [
        migrations.AlterField(
            model_name="database",
            name="release_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
