# Generated by Django 5.2 on 2025-06-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0016_database_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmmerjob",
            name="date_submitted",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
