# Generated by Django 5.2 on 2025-04-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0016_alter_database_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmmerjob",
            name="convergence_stats",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
