# Generated by Django 5.2 on 2025-06-02 08:45

import os
import json

from django.db import migrations, models

from result.models import HmmdSearchStats


def populate_number_of_hits(apps, schema_editor):
    HmmerJob = apps.get_model("search", "HmmerJob")

    for job in HmmerJob.objects.all():
        if job.number_of_hits is None and job.task and job.task.result:
            try:
                result_path = json.loads(job.task.result)
                if os.path.exists(result_path):
                    stats = HmmdSearchStats.from_file(result_path)
                    job.number_of_hits = stats.nreported
                    job.save(update_fields=["number_of_hits"])

            except Exception:
                continue


def reverse_populate_number_of_hits(apps, schema_editor):
    HmmerJob = apps.get_model("search", "HmmerJob")
    HmmerJob.objects.update(number_of_hits=None)


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0017_hmmerjob_date_submitted"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmmerjob",
            name="number_of_hits",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            populate_number_of_hits,
            reverse_populate_number_of_hits,
        ),
    ]
