# Generated by Django 5.2 on 2025-06-03 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0017_hmmerjob_convergence_stats"),
        ("search", "0018_hmmerjob_number_of_hits"),
    ]

    operations = []
