# Generated by Django 5.2 on 2025-06-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0019_merge_20250603_0900"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hmmerjob",
            name="convergence_stats",
        ),
        migrations.AddField(
            model_name="hmmerjob",
            name="exclude",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="hmmerjob",
            name="include",
            field=models.JSONField(default=list),
        ),
    ]
