# Generated by Django 5.2 on 2025-06-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0020_remove_hmmerjob_convergence_stats_hmmerjob_exclude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmmerjob",
            name="auto_run",
            field=models.BooleanField(default=False),
        ),
    ]
