# Generated by Django 5.2 on 2025-06-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0021_hmmerjob_auto_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmmerjob",
            name="calculated_input",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hmmerjob",
            name="input_type",
            field=models.CharField(
                choices=[("sequence", "Sequence"), ("hmm", "Hmm"), ("msa", "Msa"), ("uuid", "Uuid")],
                default="sequence",
                max_length=16,
            ),
        ),
    ]
