# Generated by Django 5.2 on 2025-06-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0022_hmmerjob_calculated_input_hmmerjob_input_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmmerjob",
            name="exclude_all",
            field=models.BooleanField(default=False),
        ),
    ]
