# Generated by Django 5.2 on 2025-06-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0023_hmmerjob_exclude_all"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hmmerjob",
            name="auto_run",
        ),
        migrations.AddField(
            model_name="hmmerjob",
            name="iterations",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
