# Generated by Django 5.2 on 2025-06-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0024_remove_hmmerjob_auto_run_hmmerjob_iterations"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmmerjob",
            name="email_address",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
