# Generated by Django 5.2 on 2025-06-27 09:46

import json

from django.db import migrations, models
from celery.states import SUCCESS


def populate_result_path(apps, schema_editor):
    HmmerJob = apps.get_model("search", "HmmerJob")

    for job in HmmerJob.objects.all():
        if job.task and job.task.status == SUCCESS:
            try:
                job.result_path = json.loads(job.task.result)
                job.save(update_fields=["result_path"])

            except Exception:
                continue


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0025_hmmerjob_email_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmmerjob",
            name="number_of_dropped",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hmmerjob",
            name="number_of_gained",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hmmerjob",
            name="number_of_lost",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hmmerjob",
            name="result_path",
            field=models.FilePathField(
                blank=True, null=True, path="/Users/aleksandar/Documents/djhmmer_temp/hmmer-api/results"
            ),
        ),
        migrations.RunPython(
            populate_result_path,
        ),
    ]
