# Generated by Django 5.2 on 2025-06-27 10:47

from django.db import migrations, models
from celery.states import SUCCESS


def populate_numbers(apps, schema_editor):
    HmmerJob = apps.get_model("search", "HmmerJob")

    for job in HmmerJob.objects.all():
        if job.task and job.task.status == SUCCESS:
            try:
                job.post_process()

            except Exception:
                continue


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0027_hmmerjob_number_of_included"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmmerjob",
            name="first_gained_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            populate_numbers,
        ),
    ]
