# Generated by Django 5.2 on 2025-07-01 08:33

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0028_hmmerjob_first_gained_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmmerjob",
            name="hits_index_path",
            field=models.FilePathField(
                blank=True, null=True, path=settings.HMMER.results_storage_location
            ),
        ),
    ]
