# Generated by Django 5.2 on 2025-07-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0029_hmmerjob_hits_index_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmmerjob",
            name="taxonomy_ids",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("sequence", "Sequence"),
                    ("hmm", "Hmm"),
                    ("msa", "Msa"),
                    ("uuid", "Uuid"),
                    ("multi_sequence", "Multi Sequence"),
                    ("multi_hmm", "Multi Hmm"),
                    ("multi_msa", "Multi Msa"),
                ],
                default="sequence",
                max_length=16,
            ),
        ),
    ]
