# Generated by Django 5.2 on 2025-07-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0030_hmmerjob_taxonomy_ids_alter_hmmerjob_input_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="database",
            name="status",
            field=models.CharField(
                choices=[("enabled", "Enabled"), ("disabled", "Disabled"), ("paused", "Paused")],
                default="enabled",
                max_length=16,
            ),
        ),
    ]
