# Generated by Django 5.2 on 2026-02-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0030_hmmerjob_taxonomy_ids_alter_hmmerjob_input_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hmmerjob",
            old_name="taxonomy_ids",
            new_name="exclude_taxonomy",
        ),
        migrations.AddField(
            model_name="hmmerjob",
            name="include_taxonomy",
            field=models.JSONField(default=list),
        ),
    ]
