# Generated by Django 5.2.14 on 2026-06-23 13:07

import django.core.validators
import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0032_rename_taxonomy_ids_hmmerjob_exclude_taxonomy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="database",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="E",
            field=models.FloatField(
                blank=True, default=1.0, null=True, validators=[utils.validators.StrictMinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="T",
            field=models.FloatField(
                blank=True, default=7.0, null=True, validators=[utils.validators.StrictMinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="domE",
            field=models.FloatField(
                blank=True, default=1.0, null=True, validators=[utils.validators.StrictMinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="domT",
            field=models.FloatField(
                blank=True, default=5.0, null=True, validators=[utils.validators.StrictMinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="exclude",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="exclude_taxonomy",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="incE",
            field=models.FloatField(
                blank=True, default=0.01, null=True, validators=[utils.validators.StrictMinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="incT",
            field=models.FloatField(
                blank=True, default=25.0, null=True, validators=[utils.validators.StrictMinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="incdomE",
            field=models.FloatField(
                blank=True, default=0.03, null=True, validators=[utils.validators.StrictMinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="incdomT",
            field=models.FloatField(
                blank=True, default=22.0, null=True, validators=[utils.validators.StrictMinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="include",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="include_taxonomy",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children_set",
                to="search.hmmerjob",
            ),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="pextend",
            field=models.FloatField(
                blank=True,
                default=0.4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    utils.validators.StrictMaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="hmmerjob",
            name="popen",
            field=models.FloatField(
                blank=True,
                default=0.02,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    utils.validators.StrictMaxValueValidator(0.5),
                ],
            ),
        ),
    ]
