name: Create a new image with the release number

on:
    push:
    workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=development" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
            context: .
            file: ./Dockerfile
            load: true
            push: false
            tags: |
              quay.io/microbiome-informatics/hmmer-api:${{ env.ENVIRONMENT }}-${{ github.sha }}
              quay.io/microbiome-informatics/hmmer-api:${{ env.ENVIRONMENT  }}-latest
            cache-from: type=gha
            cache-to: type=gha,mode=max

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
            registry: quay.io
            username: ${{ secrets.QUAY_USERNAME }}
            password: ${{ secrets.QUAY_PASSWORD }}

      - name: Push
        run: docker push quay.io/microbiome-informatics/hmmer-api --all-tags
